### ISSUE TITLE
Add memo code 3534875478

### ISSUE THREAD

**Issue by linecar** [stellarguard/secret-memo#13]
Please sir help me my old issue 
I am send 56.80... Stellar coin without memo. 
Please re enter memo code 3534875478
Please Sir I need help 
Hash link 
https://stellar.expert/explorer/public/tx/850f082d37a943c1e6bb5d69b465e2856ad0f05fd8bc7f7ce98a4f6c2b09eaee

**Comment by pselden** [comment]
Not related.
